version: "2"
services:

  namenode:
    image: hpcnube-namenode-image:latest
    container_name: hpcnube-namenode
    build:
      context: ./NameNode
    ports:
      - 9870:9870
    networks:
      - hpcnube-net


  resourcemanager:
    image: hpcnube-resourcemanager-image:latest
    container_name: hpcnube-resourcemanager
    build:
      context: ./ResourceManager
    ports:
      - 8088:8088
    networks:
      - hpcnube-net


  hpcnube-dnnm:
    image: hpcnube-dnnm-image:latest
    build:
      context: ./DataNode-NodeManager
    networks:
      - hpcnube-net


  frontend:
    image: hpcnube-frontend-image:latest
    container_name: hpcnube-frontend
    build:
      context: ./Frontend
    ports:
      - 22:22
    networks:
      - hpcnube-net
    volumes:
       - type: bind
         source: ./src/codigos
         target: /home/luser/codigos
       - type: bind
         source: ./src/datos
         target: /home/luser/datos


networks:
  hpcnube-net:
    name: hpcnube-net



    